
version: '3'
services:
  fizz_buzz_db:
    container_name: fizz-buzz-db
    image: "postgres:14.5"
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  fizz_buzz_backend:
    container_name: fizz-buzz-backend
    build: 
      context: ../backend
    restart: always
    env_file:
      - ../backend/.env
      - ./.env
    environment:
      - PORT=8000
    ports:
      - 3000:8000
    depends_on:
      - fizz_buzz_db
    working_dir: /app
    command: npm run start:watch

  fizz_buzz_frontend:
    container_name: fizz-buzz-frontend
    build: 
      context: ../frontend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - fizz_buzz_backend
    working_dir: /app
    command: npm run serve

volumes:
  pgdata:
